# Generated by Django 2.2.1 on 2019-05-04 04:57

from django.conf import settings
import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.TextField(null=True)),
                ('code', models.TextField(null=True)),
                ('fyle_category', models.TextField(null=True)),
                ('sub_category', models.TextField(null=True)),
                ('enabled', models.BooleanField()),
                ('code1', models.TextField(null=True)),
                ('code2', models.TextField(null=True)),
                ('code3', models.TextField(null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='CostCenter',
            fields=[
                ('id', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('name', models.TextField(null=True)),
                ('description', models.TextField(null=True)),
                ('code1', models.TextField(null=True)),
                ('code2', models.TextField(null=True)),
                ('code3', models.TextField(null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('employee_email', models.EmailField(max_length=254, null=True)),
                ('employee_code', models.TextField(null=True)),
                ('full_name', models.TextField(null=True)),
                ('location', models.TextField(null=True)),
                ('level', models.TextField(null=True)),
                ('business_unit', models.TextField(null=True)),
                ('department', models.TextField(null=True)),
                ('sub_department', models.TextField(null=True)),
                ('title', models.TextField(null=True)),
                ('disabled', models.BooleanField()),
                ('org_id', models.TextField(null=True)),
                ('org_name', models.TextField(null=True)),
                ('code1', models.TextField(null=True)),
                ('code2', models.TextField(null=True)),
                ('code3', models.TextField(null=True)),
                ('default_cost_center', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='fyle.CostCenter')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('name', models.TextField(null=True)),
                ('description', models.TextField(null=True)),
                ('active', models.BooleanField()),
                ('code1', models.TextField(null=True)),
                ('code2', models.TextField(null=True)),
                ('code3', models.TextField(null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Expense',
            fields=[
                ('id', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('currency', models.TextField(null=True)),
                ('amount', models.FloatField(null=True)),
                ('foreign_currency', models.TextField(null=True)),
                ('foreign_amount', models.FloatField(null=True)),
                ('purpose', models.TextField(null=True)),
                ('custom_properties', django.contrib.postgres.fields.jsonb.JSONField(null=True)),
                ('reimbursable', models.BooleanField()),
                ('state', models.TextField(null=True)),
                ('spent_at', models.DateTimeField(null=True)),
                ('created_at', models.DateTimeField(null=True)),
                ('approved_at', models.DateTimeField(null=True)),
                ('verified', models.BooleanField()),
                ('verified_at', models.DateTimeField(null=True)),
                ('reimbursed_at', models.DateTimeField(null=True)),
                ('vendor', models.TextField(null=True)),
                ('category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='fyle.Category')),
                ('cost_center', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='fyle.CostCenter')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fyle.Employee')),
                ('project', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='fyle.Project')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Advance',
            fields=[
                ('id', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('currency', models.TextField(null=True)),
                ('amount', models.FloatField(null=True)),
                ('purpose', models.TextField(null=True)),
                ('issued_at', models.DateTimeField(null=True)),
                ('payment_mode', models.TextField(null=True)),
                ('original_currency', models.TextField(null=True)),
                ('original_amount', models.FloatField(null=True)),
                ('reference', models.TextField(null=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fyle.Employee')),
                ('project', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='fyle.Project')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
