# Generated by Django 2.2.1 on 2019-05-18 04:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fyle', '0004_auto_20190516_0718'),
    ]

    operations = [
        migrations.AddField(
            model_name='importbatch',
            name='detailed_status',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='importbatch',
            name='status',
            field=models.CharField(choices=[('S', 'Started'), ('C', 'Completed'), ('F', 'Failed')], default='S', max_length=2),
        ),
    ]
